### ISSUE TITLE
Needs updating 1.21.1

### ISSUE THREAD

**Issue by roracle** [DragonPoika/Mailboxes#1]
I changed the crafting configuration and was able to get the knowledge book, but no mailbox. I don't know enough about datapacks to fix this myself.

**Comment by ToastedDragon** [comment]
Hi.
No.
This pack is discontinued as updating it to 1.20.5 would be a lot of work and we are also humans, with lives to live. We recently had to do this to Greenery, our latest pack, and it delayed it with about half a year.

This is because Mojang changed a major way in how items handle data, which meant we had to redo the whole of Greenery. We're not doing this for Mailboxes. I dearly apologize for any inconvenience. 

Just a little notice, the pack version is on the pack page and Minecraft even says that it isn't for this version.

Closing this as invalid & as a wont fix.
